# --------------------------------------------------------------------
#
# !\file makefile
# !\brief Makefile for building the project.
# !\author Colin J.D. Stewart
#
# --------------------------------------------------------------------
#             Copyright (c) 2026. Colin J.D. Stewart
#                     All rights reserved
# --------------------------------------------------------------------

#
# DO NOT EDIT THIS FILE. FOR CUSTOMISATION

# -----------------------------------
# Directory layout
# -----------------------------------
SRC_DIR := src
BIN_DIR := $(SRC_DIR)/bin
LIB_DIR := $(SRC_DIR)/lib
INC_DIR := $(SRC_DIR)/inc

# automatically collect every subdirectory beneath the public include
# tree. This saves callers from having to add -I for each new component
# manually; the recursive find handles arbitrarily deep hierarchies.
#
# Note: the find pipes stderr to /dev/null in case the directory doesn't
# exist yet (e.g. early in a fresh checkout).
INC_SUBDIRS := $(shell find $(INC_DIR) -type d 2>/dev/null)
INC_SUBDIR_FLAGS := $(foreach dir,$(INC_SUBDIRS),-I$(dir))
OBJ_DIR := $(SRC_DIR)/bld
OUT_DIR := bld

TST_DIR := $(SRC_DIR)/tst
TST_UT_DIR := $(TST_DIR)/ut
TST_SY_DIR := $(TST_DIR)/sy

# -----------------------------------
# Dependency include scanning (dep/*)
# -----------------------------------
DEP_ROOT := dep
DEP_ROOT_ABS := $(abspath $(DEP_ROOT))
DEP_MAP_DIR := $(OBJ_DIR)/depinc
DEP_NAMES := $(shell [ -d "$(DEP_ROOT)" ] && for p in "$(DEP_ROOT)"/*; do [ -d "$$p" ] && basename "$$p"; done || true)
DEP_INC_DIRS := $(wildcard $(DEP_ROOT)/*/src/inc)
DEP_INC_FLAGS := $(foreach dir,$(DEP_INC_DIRS),-I$(dir))

# -----------------------------------
# Toolchain
# -----------------------------------
CXX ?= g++
AR ?= ar
EXE_LINKER ?= $(CXX)
SHARED_LINKER ?= $(CXX)

# MODE and CXX_STD may be set in makefile.project.mk
MODE ?= debug
CXX_STD ?= c++20
FILTER ?= $(filter)

# -----------------------------------
# Assembly mode override helpers
# -----------------------------------

# Strip an optional .m32 / .m64 marker that appears immediately before
# the source extension, so:
#   foo.m32.S   -> foo.S
#   foo.m64.asm -> foo.asm
strip_asm_mode_marker = $(patsubst %.m32.S,%.S,$(patsubst %.m64.S,%.S,$(patsubst %.m32.asm,%.asm,$(patsubst %.m64.asm,%.asm,$1))))

# Convert a source path under src/ to its object path under src/bld/,
# while also stripping the optional mode marker from the basename.
src_to_obj = $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(patsubst $(SRC_DIR)/%.S,$(OBJ_DIR)/%.o,$(patsubst $(SRC_DIR)/%.asm,$(OBJ_DIR)/%.o,$(call strip_asm_mode_marker,$1)))))
src_to_pic_obj = $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.pic.o,$(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.pic.o,$(patsubst $(SRC_DIR)/%.S,$(OBJ_DIR)/%.pic.o,$(patsubst $(SRC_DIR)/%.asm,$(OBJ_DIR)/%.pic.o,$(call strip_asm_mode_marker,$1)))))

# Given a list of flagged sources, derive the matching plain source names
# so they can be excluded from the normal source list.
flagged_to_plain = $(foreach f,$1,$(call strip_asm_mode_marker,$(f)))

# -----------------------------------
# Flags and options
# -----------------------------------
CPPFLAGS += -I$(INC_DIR) $(INC_SUBDIR_FLAGS) $(DEP_INC_FLAGS) -I$(DEP_MAP_DIR) -MMD -MP
CXXFLAGS += -std=$(CXX_STD) -Wall -Wextra -Wpedantic
LDFLAGS +=
LDLIBS +=
SFLAGS += $(filter-out -std=%,$(CXXFLAGS))
ASMFLAGS += $(filter-out -std=%,$(CXXFLAGS))
S_PICFLAGS += $(filter-out -std=%,$(CXXFLAGS)) -fPIC
ASM_PICFLAGS += $(filter-out -std=%,$(CXXFLAGS)) -fPIC

ifeq ($(MODE),release)
  CXXFLAGS += -O2 -DNDEBUG
else
  CXXFLAGS += -O0 -g
endif

# Project hooks
CPPFLAGS += $(USER_CPPFLAGS) -I$(DEP_MAP_DIR)
CXXFLAGS += $(USER_CXXFLAGS)
LDFLAGS += $(USER_LDFLAGS)
LDLIBS += $(USER_LDLIBS)
SFLAGS += $(USER_SFLAGS)
ASMFLAGS += $(USER_ASMFLAGS)
S_PICFLAGS += $(USER_S_PICFLAGS)
ASM_PICFLAGS += $(USER_ASM_PICFLAGS)

# -----------------------------------
# Architecture-specific assembly flag filtering
# -----------------------------------

# Remove flags that should not leak into a forced 32-bit assembly build.
SFLAGS_M32 := $(filter-out -m64 -m32 -mcmodel=%,$(SFLAGS))
ASMFLAGS_M32 := $(filter-out -m64 -m32 -mcmodel=%,$(ASMFLAGS))
S_PICFLAGS_M32 := $(filter-out -m64 -m32 -mcmodel=%,$(S_PICFLAGS))
ASM_PICFLAGS_M32 := $(filter-out -m64 -m32 -mcmodel=%,$(ASM_PICFLAGS))

# Remove conflicting architecture selectors from forced 64-bit builds.
SFLAGS_M64 := $(filter-out -m32 -m64,$(SFLAGS))
ASMFLAGS_M64 := $(filter-out -m32 -m64,$(ASMFLAGS))
S_PICFLAGS_M64 := $(filter-out -m32 -m64,$(S_PICFLAGS))
ASM_PICFLAGS_M64 := $(filter-out -m32 -m64,$(ASM_PICFLAGS))

# -----------------------------------
# Output artefacts
# -----------------------------------
EXEC_OUT   ?= $(OUT_DIR)/$(BIN_NAME)
STATIC_OUT ?= $(OUT_DIR)/lib$(LIB_BASENAME).a
SHARED_OUT ?= $(OUT_DIR)/lib$(LIB_BASENAME).so

BUILD_TARGETS :=

ifeq ($(BUILD_EXE),1)
  BUILD_TARGETS += exe
endif

ifeq ($(BUILD_STATIC),1)
  BUILD_TARGETS += static
endif

ifeq ($(BUILD_SHARED),1)
  BUILD_TARGETS += shared
endif

ifeq ($(strip $(BUILD_TARGETS)),)
  $(warning No build targets enabled (BUILD_EXE/STATIC/SHARED all 0))
endif

# -----------------------------------
# Source discovery
# -----------------------------------

BIN_SOURCES := $(wildcard $(BIN_DIR)/*.cpp)

BIN_S_FLAGGED_SOURCES := $(wildcard $(BIN_DIR)/*.m32.S) $(wildcard $(BIN_DIR)/*.m64.S)
BIN_S_PLAIN_SOURCES := $(filter-out $(call flagged_to_plain,$(BIN_S_FLAGGED_SOURCES)),$(wildcard $(BIN_DIR)/*.S))

BIN_ASM_FLAGGED_SOURCES := $(wildcard $(BIN_DIR)/*.m32.asm) $(wildcard $(BIN_DIR)/*.m64.asm)
BIN_ASM_PLAIN_SOURCES := $(filter-out $(call flagged_to_plain,$(BIN_ASM_FLAGGED_SOURCES)),$(wildcard $(BIN_DIR)/*.asm))

LIB_CPP_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.cpp' || true)
LIB_C_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.c' || true)

LIB_S_FLAGGED_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f \( -name '*.m32.S' -o -name '*.m64.S' \) || true)
LIB_S_PLAIN_SOURCES := $(filter-out $(call flagged_to_plain,$(LIB_S_FLAGGED_SOURCES)),$(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.S' || true))

LIB_ASM_FLAGGED_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f \( -name '*.m32.asm' -o -name '*.m64.asm' \) || true)
LIB_ASM_PLAIN_SOURCES := $(filter-out $(call flagged_to_plain,$(LIB_ASM_FLAGGED_SOURCES)),$(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.asm' || true))

BIN_S_SOURCES := $(BIN_S_PLAIN_SOURCES) $(BIN_S_FLAGGED_SOURCES)
BIN_ASM_SOURCES := $(BIN_ASM_PLAIN_SOURCES) $(BIN_ASM_FLAGGED_SOURCES)

LIB_S_SOURCES := $(LIB_S_PLAIN_SOURCES) $(LIB_S_FLAGGED_SOURCES)
LIB_ASM_SOURCES := $(LIB_ASM_PLAIN_SOURCES) $(LIB_ASM_FLAGGED_SOURCES)

# ------------------------------------
# Object file lists
# ------------------------------------

LIB_SOURCES := $(LIB_CPP_SOURCES) $(LIB_C_SOURCES) $(LIB_S_SOURCES) $(LIB_ASM_SOURCES)

BIN_OBJECTS := $(foreach f,$(BIN_SOURCES),$(call src_to_obj,$(f)))
BIN_OBJECTS += $(foreach f,$(BIN_S_SOURCES),$(call src_to_obj,$(f)))
BIN_OBJECTS += $(foreach f,$(BIN_ASM_SOURCES),$(call src_to_obj,$(f)))

LIB_CPP_OBJECTS := $(foreach f,$(LIB_CPP_SOURCES),$(call src_to_obj,$(f)))
LIB_C_OBJECTS := $(foreach f,$(LIB_C_SOURCES),$(call src_to_obj,$(f)))
LIB_S_OBJECTS := $(foreach f,$(LIB_S_SOURCES),$(call src_to_obj,$(f)))
LIB_ASM_OBJECTS := $(foreach f,$(LIB_ASM_SOURCES),$(call src_to_obj,$(f)))

LIB_CPP_PIC_OBJECTS := $(foreach f,$(LIB_CPP_SOURCES),$(call src_to_pic_obj,$(f)))
LIB_C_PIC_OBJECTS := $(foreach f,$(LIB_C_SOURCES),$(call src_to_pic_obj,$(f)))
LIB_S_PIC_OBJECTS := $(foreach f,$(LIB_S_SOURCES),$(call src_to_pic_obj,$(f)))
LIB_ASM_PIC_OBJECTS := $(foreach f,$(LIB_ASM_SOURCES),$(call src_to_pic_obj,$(f)))

LIB_OBJECTS := $(LIB_CPP_OBJECTS) $(LIB_C_OBJECTS) $(LIB_S_OBJECTS) $(LIB_ASM_OBJECTS)
LIB_PIC_OBJECTS := $(LIB_CPP_PIC_OBJECTS) $(LIB_C_PIC_OBJECTS) $(LIB_S_PIC_OBJECTS) $(LIB_ASM_PIC_OBJECTS)
ALL_OBJECTS := $(BIN_OBJECTS) $(LIB_OBJECTS) $(LIB_PIC_OBJECTS)

# -----------------------------------
# Verbose mode
# -----------------------------------
VERBOSE ?= 0
ifeq ($(VERBOSE),1)
  Q :=
else
  Q := @
endif

# Suppress recursive-make directory enter/leave messages
MAKEFLAGS += --no-print-directory

# -----------------------------------
# Compilation rules
# -----------------------------------

# C++ sources in src/bin (no PIC)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.cpp
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C++ (bin): $<"
	$(Q)$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/bin (.m32.S files, preprocessed)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.m32.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, bin, m32): $<"
	$(Q)$(CXX) $(CPPFLAGS) $(SFLAGS_M32) -m32 -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/bin (.m64.S files, preprocessed)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.m64.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, bin, m64): $<"
	$(Q)$(CXX) $(CPPFLAGS) $(SFLAGS_M64) -m64 -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/bin (.S files, preprocessed)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, bin): $<"
	$(Q)$(CXX) $(CPPFLAGS) $(SFLAGS) -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/bin (.m32.asm files, preprocessed)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.m32.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, bin, m32): $<"
	$(Q)$(CXX) $(CPPFLAGS) $(ASMFLAGS_M32) -m32 -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/bin (.m64.asm files, preprocessed)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.m64.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, bin, m64): $<"
	$(Q)$(CXX) $(CPPFLAGS) $(ASMFLAGS_M64) -m64 -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/bin (.asm files, preprocessed)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, bin): $<"
	$(Q)$(CXX) $(CPPFLAGS) $(ASMFLAGS) -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C++ sources in src/lib
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.cpp
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C++ (lib): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(CXXFLAGS) -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C sources in src/lib
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.c
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C (lib): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) -x c -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C++ sources in src/lib compiled with PIC for shared library target
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.cpp
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C++ (lib,pic): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(CXXFLAGS) -fPIC -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C sources in src/lib compiled with PIC for shared library target
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.c
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C (lib,pic): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) -fPIC -x c -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m32.S files, preprocessed)
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.m32.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, m32): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(SFLAGS_M32) -m32 -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m64.S files, preprocessed)
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.m64.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, m64): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(SFLAGS_M64) -m64 -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.S files, preprocessed)
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(SFLAGS) -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m32.S files, preprocessed) compiled with PIC
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.m32.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, pic, m32): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(S_PICFLAGS_M32) -m32 -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m64.S files, preprocessed) compiled with PIC
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.m64.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, pic, m64): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(S_PICFLAGS_M64) -m64 -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.S files, preprocessed) compiled with PIC
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.S
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.S, pic): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(S_PICFLAGS) -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m32.asm files, preprocessed)
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.m32.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, m32): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(ASMFLAGS_M32) -m32 -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m64.asm files, preprocessed)
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.m64.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, m64): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(ASMFLAGS_M64) -m64 -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.asm files, raw assembly)
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(ASMFLAGS) -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m32.asm files, preprocessed) compiled with PIC
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.m32.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, pic, m32): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(ASM_PICFLAGS_M32) -m32 -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.m64.asm files, preprocessed) compiled with PIC
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.m64.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, pic, m64): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(ASM_PICFLAGS_M64) -m64 -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# Assembly sources in src/lib (.asm files, raw assembly) compiled with PIC
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.asm
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "ASM (.asm, pic): $<"
	$(Q)$(CXX) -I$(INC_DIR)/$(dir $*) $(CPPFLAGS) $(ASM_PICFLAGS) -x assembler-with-cpp -MT $@ -MF $(@:.o=.d) -c $< -o $@

# -----------------------------------
# Output directory
# -----------------------------------
$(OUT_DIR):
	$(Q)mkdir -p $(OUT_DIR)

# -----------------------------------
# Executable
# -----------------------------------
.DEFAULT_GOAL := all

all: dep-incmap $(BUILD_TARGETS)

exe: dep-incmap $(EXEC_OUT)

$(EXEC_OUT): $(BIN_OBJECTS) $(LIB_OBJECTS) | $(OUT_DIR)
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "Link (exe): $@"
	$(Q)$(EXE_LINKER) $(LDFLAGS) -o $@ $^ $(LDLIBS)

# -----------------------------------
# Static library
# -----------------------------------
static: dep-incmap $(STATIC_OUT)

$(STATIC_OUT): $(LIB_OBJECTS) | $(OUT_DIR)
	$(Q)echo "Archive (static): $@"
	$(Q)rm -f $@
	$(Q)$(AR) rcs $@ $^

# -----------------------------------
# Shared library
# -----------------------------------
shared: dep-incmap $(SHARED_OUT)

$(SHARED_OUT): $(LIB_PIC_OBJECTS) | $(OUT_DIR)
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "Link (shared): $@"
	$(Q)$(SHARED_LINKER) -shared $(LDFLAGS) -o $@ $^ $(LDLIBS)

# -----------------------------------
# Auto dependencies
# -----------------------------------
DEPS := $(ALL_OBJECTS:.o=.d)
-include $(DEPS)

# -----------------------------------
# PHONY targets
# -----------------------------------
.PHONY: help
help:
	@echo "Targets:"
	@echo "  all        Build enabled targets (BUILD_EXE/STATIC/SHARED)"
	@echo "  exe        Build executable"
	@echo "  static     Build static library"
	@echo "  shared     Build shared library"
	@echo "  tests      Run unit + system tests (if present)"
	@echo "  ut         Run unit tests"
	@echo "  sy         Run system tests"
	@echo "  clean      Remove build artefacts"
	@echo "  distclean  Same as clean"
	@echo ""
	@echo "Options:"
	@echo "  MODE=debug|release"
	@echo "  VERBOSE=1"
	@echo "  FILTER=<substring>   Filter tests by name (e.g. make tests FILTER=math)"

.PHONY: dep-incmap
dep-incmap:
	$(Q)mkdir -p "$(DEP_MAP_DIR)"
	$(Q)for d in $(DEP_NAMES); do \
		if [ -d "$(DEP_ROOT)/$$d/src/inc/$$d" ]; then \
			ln -sfn "$(DEP_ROOT_ABS)/$$d/src/inc/$$d" "$(DEP_MAP_DIR)/$$d"; \
		elif [ -d "$(DEP_ROOT)/$$d/src/inc" ]; then \
			ln -sfn "$(DEP_ROOT_ABS)/$$d/src/inc" "$(DEP_MAP_DIR)/$$d"; \
		fi; \
	done

.PHONY: ut
ut:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" all; \
		if [ -n "$(FILTER)" ]; then \
			echo "Running filtered unit tests (FILTER=$(FILTER))..."; \
			found=0; \
			for bin in "$(TST_UT_DIR)"/bld/TEST_*; do \
				if [ -x "$$bin" ] && [ -f "$$bin" ]; then \
					base="$$(basename "$$bin")"; \
					base_lc="$$(printf "%s" "$$base" | tr '[:upper:]' '[:lower:]')"; \
					filter_lc="$$(printf "%s" "$(FILTER)" | tr '[:upper:]' '[:lower:]')"; \
					case "$$base_lc" in \
						*$$filter_lc*) \
							echo "→ Running $$bin"; \
							"$$bin" || exit 1; \
							found=1; \
							;; \
					esac; \
				fi; \
			done; \
			if [ "$$found" -eq 0 ]; then \
				echo "No unit tests matched FILTER=$(FILTER)"; \
			fi; \
		else \
			$(MAKE) -C "$(TST_UT_DIR)" run; \
		fi; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

.PHONY: sy
sy: all
	@if [ -x "$(TST_SY_DIR)/runner" ]; then \
		FILTER="$(FILTER)" "$(TST_SY_DIR)/runner"; \
	else \
		echo "No system test runner found at $(TST_SY_DIR)/runner"; \
	fi

.PHONY: tests
tests: ut sy

.PHONY: clean clean-tests clean-all distclean

clean-all:
	$(Q)echo "Cleaning build artefacts..."
	$(Q)for d in "$(OBJ_DIR)" "$(OUT_DIR)"; do \
		mkdir -p "$$d"; \
		find "$$d" -mindepth 1 \( -type f -o -type l \) ! -name ".gitignore" -delete; \
		find "$$d" -mindepth 1 -type d -empty -delete; \
	done

clean-tests:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" clean; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

clean: clean-all clean-tests

distclean: clean

.PHONY: all exe static shared tests ut sy dep-incmap clean clean-all clean-tests distclean