# --------------------------------------------------------------------
#
# !\file makefile
# !\brief Makefile for building the project.
# !\author Colin J.D. Stewart
#
# --------------------------------------------------------------------
#             Copyright (c) 2026. Colin J.D. Stewart
#                     All rights reserved
# --------------------------------------------------------------------

#
# DO NOT EDIT THIS FILE. FOR CUSTOMISATION

# -----------------------------------
# Directory layout
# -----------------------------------
SRC_DIR := src
BIN_DIR := $(SRC_DIR)/bin
LIB_DIR := $(SRC_DIR)/lib
INC_DIR := $(SRC_DIR)/inc

# automatically collect every subdirectory beneath the public include
# tree. This saves callers from having to add -I for each new component
# manually; the recursive find handles arbitrarily deep hierarchies.
#
# Note: the find pipes stderr to /dev/null in case the directory doesn't
# exist yet (e.g. early in a fresh checkout).
INC_SUBDIRS := $(shell find $(INC_DIR) -type d 2>/dev/null)
INC_SUBDIR_FLAGS := $(foreach dir,$(INC_SUBDIRS),-I$(dir))
OBJ_DIR := $(SRC_DIR)/bld
OUT_DIR := bld
abi_obj_dir = $(OBJ_DIR)/$(1)
abi_out_dir = $(OUT_DIR)/$(1)

TST_DIR := $(SRC_DIR)/tst
TST_UT_DIR := $(TST_DIR)/ut
TST_SY_DIR := $(TST_DIR)/sy

# -----------------------------------
# Dependency include scanning (dep/*)
# -----------------------------------
DEP_ROOT := dep
DEP_ROOT_ABS := $(abspath $(DEP_ROOT))
# Keep the dependency include map shared across ABI variants; the
# symlinked include tree itself is architecture-neutral.
DEP_MAP_DIR := $(OBJ_DIR)/depinc
DEP_NAMES := $(shell [ -d "$(DEP_ROOT)" ] && for p in "$(DEP_ROOT)"/*; do [ -d "$$p" ] && basename "$$p"; done || true)
DEP_INC_DIRS := $(wildcard $(DEP_ROOT)/*/src/inc)
DEP_INC_FLAGS := $(foreach dir,$(DEP_INC_DIRS),-I$(dir))

# -----------------------------------
# Toolchain
# -----------------------------------
CXX ?= g++
AR ?= ar
EXE_LINKER ?= $(CXX)
SHARED_LINKER ?= $(CXX)

# MODE and CXX_STD may be set in makefile.project.mk
MODE ?= debug
CXX_STD ?= c++20
FILTER ?= $(filter)

# -----------------------------------
# Assembly mode override helpers
# -----------------------------------

# Strip an optional .m32 / .m64 marker that appears immediately before
# the source extension, so:
#   foo.m32.S   -> foo.S
#   foo.m64.asm -> foo.asm
strip_asm_mode_marker = $(patsubst %.m32.S,%.S,$(patsubst %.m64.S,%.S,$(patsubst %.m32.asm,%.asm,$(patsubst %.m64.asm,%.asm,$(1)))))

# Convert a source path under src/ to its ABI-specific object path under
# src/bld/<abi>/, while also stripping the optional mode marker from the
# basename.
src_to_obj = $(patsubst $(SRC_DIR)/%.cpp,$(call abi_obj_dir,$(1))/%.o,$(patsubst $(SRC_DIR)/%.c,$(call abi_obj_dir,$(1))/%.o,$(patsubst $(SRC_DIR)/%.S,$(call abi_obj_dir,$(1))/%.o,$(patsubst $(SRC_DIR)/%.asm,$(call abi_obj_dir,$(1))/%.o,$(call strip_asm_mode_marker,$(2))))))
src_to_pic_obj = $(patsubst $(SRC_DIR)/%.cpp,$(call abi_obj_dir,$(1))/%.pic.o,$(patsubst $(SRC_DIR)/%.c,$(call abi_obj_dir,$(1))/%.pic.o,$(patsubst $(SRC_DIR)/%.S,$(call abi_obj_dir,$(1))/%.pic.o,$(patsubst $(SRC_DIR)/%.asm,$(call abi_obj_dir,$(1))/%.pic.o,$(call strip_asm_mode_marker,$(2))))))

# Given a list of flagged sources, derive the matching plain source names
# so they can be excluded from the normal source list.
flagged_to_plain = $(foreach f,$(1),$(call strip_asm_mode_marker,$(f)))

# -----------------------------------
# Flags and options
# -----------------------------------
CPPFLAGS += -I$(INC_DIR) $(INC_SUBDIR_FLAGS) $(DEP_INC_FLAGS) -I$(DEP_MAP_DIR) -MMD -MP
CXXFLAGS += -std=$(CXX_STD) -Wall -Wextra -Wpedantic
LDFLAGS +=
LDLIBS +=
SFLAGS += $(filter-out -std=%,$(CXXFLAGS))
ASMFLAGS += $(filter-out -std=%,$(CXXFLAGS))
S_PICFLAGS += $(filter-out -std=%,$(CXXFLAGS)) -fPIC
ASM_PICFLAGS += $(filter-out -std=%,$(CXXFLAGS)) -fPIC

ifeq ($(MODE),release)
  CXXFLAGS += -O2 -DNDEBUG
else
  CXXFLAGS += -O0 -g
endif

# Project hooks
CPPFLAGS += $(USER_CPPFLAGS) -I$(DEP_MAP_DIR)
CXXFLAGS += $(USER_CXXFLAGS)
LDFLAGS += $(USER_LDFLAGS)
LDLIBS += $(USER_LDLIBS)
SFLAGS += $(USER_SFLAGS)
ASMFLAGS += $(USER_ASMFLAGS)
S_PICFLAGS += $(USER_S_PICFLAGS)
ASM_PICFLAGS += $(USER_ASM_PICFLAGS)

# -----------------------------------
# Architecture-specific flag filtering
# -----------------------------------

arch_filter_m32 = $(filter-out -m64 -m32 -mcmodel=%,$(1))
arch_filter_m64 = $(filter-out -m32 -m64,$(1))

ARCHFLAGS_m32 := -m32
ARCHFLAGS_m64 := -m64

# Bare linkers such as ld/ld.lld do not accept compiler-style -m32/-m64
# switches. Keep separate linker arch flags so projects that link via ld
# can rely on explicit emulation flags in USER_LDFLAGS instead.
is_ld_linker = $(strip $(filter ld ld.% %ld %ld.%,$(notdir $(1))))
EXE_ARCHFLAGS_m32 ?= $(if $(call is_ld_linker,$(EXE_LINKER)),,$(ARCHFLAGS_m32))
EXE_ARCHFLAGS_m64 ?= $(if $(call is_ld_linker,$(EXE_LINKER)),,$(ARCHFLAGS_m64))
SHARED_ARCHFLAGS_m32 ?= $(if $(call is_ld_linker,$(SHARED_LINKER)),,$(ARCHFLAGS_m32))
SHARED_ARCHFLAGS_m64 ?= $(if $(call is_ld_linker,$(SHARED_LINKER)),,$(ARCHFLAGS_m64))

CXXFLAGS_m32 := $(call arch_filter_m32,$(CXXFLAGS))
CXXFLAGS_m64 := $(call arch_filter_m64,$(CXXFLAGS))
LDFLAGS_m32 := $(call arch_filter_m32,$(LDFLAGS))
LDFLAGS_m64 := $(call arch_filter_m64,$(LDFLAGS))
SFLAGS_m32 := $(call arch_filter_m32,$(SFLAGS))
SFLAGS_m64 := $(call arch_filter_m64,$(SFLAGS))
ASMFLAGS_m32 := $(call arch_filter_m32,$(ASMFLAGS))
ASMFLAGS_m64 := $(call arch_filter_m64,$(ASMFLAGS))
S_PICFLAGS_m32 := $(call arch_filter_m32,$(S_PICFLAGS))
S_PICFLAGS_m64 := $(call arch_filter_m64,$(S_PICFLAGS))
ASM_PICFLAGS_m32 := $(call arch_filter_m32,$(ASM_PICFLAGS))
ASM_PICFLAGS_m64 := $(call arch_filter_m64,$(ASM_PICFLAGS))

# -----------------------------------
# ABI selection
# -----------------------------------
BUILD_M32 ?= 0
BUILD_M64 ?= 1

BUILD_ABIS :=

ifeq ($(BUILD_M32),1)
  BUILD_ABIS += m32
endif

ifeq ($(BUILD_M64),1)
  BUILD_ABIS += m64
endif

ifeq ($(strip $(BUILD_ABIS)),)
  $(warning No ABIs enabled (BUILD_M32/BUILD_M64 both 0))
endif

SINGLE_ABI := $(if $(filter 1,$(words $(BUILD_ABIS))),$(firstword $(BUILD_ABIS)))

default_exec_out = $(call abi_out_dir,$(1))/$(BIN_NAME)
default_static_out = $(call abi_out_dir,$(1))/lib$(LIB_BASENAME).a
default_shared_out = $(call abi_out_dir,$(1))/lib$(LIB_BASENAME).so

ifneq ($(strip $(EXEC_OUT)),)
ifneq ($(words $(BUILD_ABIS)),1)
  $(warning EXEC_OUT is ignored when multiple ABIs are enabled; use EXEC_OUT_m32 / EXEC_OUT_m64)
endif
endif

ifneq ($(strip $(STATIC_OUT)),)
ifneq ($(words $(BUILD_ABIS)),1)
  $(warning STATIC_OUT is ignored when multiple ABIs are enabled; use STATIC_OUT_m32 / STATIC_OUT_m64)
endif
endif

ifneq ($(strip $(SHARED_OUT)),)
ifneq ($(words $(BUILD_ABIS)),1)
  $(warning SHARED_OUT is ignored when multiple ABIs are enabled; use SHARED_OUT_m32 / SHARED_OUT_m64)
endif
endif

define init_abi_outputs
EXEC_OUT_$1 ?= $(if $(and $(filter $1,$(SINGLE_ABI)),$(strip $(EXEC_OUT))),$(EXEC_OUT),$(call default_exec_out,$1))
STATIC_OUT_$1 ?= $(if $(and $(filter $1,$(SINGLE_ABI)),$(strip $(STATIC_OUT))),$(STATIC_OUT),$(call default_static_out,$1))
SHARED_OUT_$1 ?= $(if $(and $(filter $1,$(SINGLE_ABI)),$(strip $(SHARED_OUT))),$(SHARED_OUT),$(call default_shared_out,$1))
endef

$(foreach abi,m32 m64,$(eval $(call init_abi_outputs,$(abi))))

BUILD_TARGETS :=

ifeq ($(BUILD_EXE),1)
  BUILD_TARGETS += exe
endif

ifeq ($(BUILD_STATIC),1)
  BUILD_TARGETS += static
endif

ifeq ($(BUILD_SHARED),1)
  BUILD_TARGETS += shared
endif

ifeq ($(strip $(BUILD_TARGETS)),)
  $(warning No build targets enabled (BUILD_EXE/STATIC/SHARED all 0))
endif

# -----------------------------------
# Source discovery
# -----------------------------------

BIN_SOURCES := $(wildcard $(BIN_DIR)/*.cpp)

LIB_CPP_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.cpp' || true)
LIB_C_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.c' || true)

# ------------------------------------
# Object file lists
# ------------------------------------

define define_abi_objects
BIN_S_FLAGGED_SOURCES_$1 := $(wildcard $(BIN_DIR)/*.$1.S)
BIN_S_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(BIN_S_FLAGGED_SOURCES_$1)),$(wildcard $(BIN_DIR)/*.S))

BIN_ASM_FLAGGED_SOURCES_$1 := $(wildcard $(BIN_DIR)/*.$1.asm)
BIN_ASM_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(BIN_ASM_FLAGGED_SOURCES_$1)),$(wildcard $(BIN_DIR)/*.asm))

LIB_S_FLAGGED_SOURCES_$1 := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.$1.S' || true)
LIB_S_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(LIB_S_FLAGGED_SOURCES_$1)),$(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.S' || true))

LIB_ASM_FLAGGED_SOURCES_$1 := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.$1.asm' || true)
LIB_ASM_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(LIB_ASM_FLAGGED_SOURCES_$1)),$(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.asm' || true))

BIN_S_SOURCES_$1 := $$(BIN_S_PLAIN_SOURCES_$1) $$(BIN_S_FLAGGED_SOURCES_$1)
BIN_ASM_SOURCES_$1 := $$(BIN_ASM_PLAIN_SOURCES_$1) $$(BIN_ASM_FLAGGED_SOURCES_$1)

LIB_S_SOURCES_$1 := $$(LIB_S_PLAIN_SOURCES_$1) $$(LIB_S_FLAGGED_SOURCES_$1)
LIB_ASM_SOURCES_$1 := $$(LIB_ASM_PLAIN_SOURCES_$1) $$(LIB_ASM_FLAGGED_SOURCES_$1)

LIB_SOURCES_$1 := $(LIB_CPP_SOURCES) $(LIB_C_SOURCES) $$(LIB_S_SOURCES_$1) $$(LIB_ASM_SOURCES_$1)

BIN_OBJECTS_$1 := $$(foreach f,$$(BIN_SOURCES),$$(call src_to_obj,$1,$$(f)))
BIN_OBJECTS_$1 += $$(foreach f,$$(BIN_S_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))
BIN_OBJECTS_$1 += $$(foreach f,$$(BIN_ASM_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))

LIB_CPP_OBJECTS_$1 := $$(foreach f,$$(LIB_CPP_SOURCES),$$(call src_to_obj,$1,$$(f)))
LIB_C_OBJECTS_$1 := $$(foreach f,$$(LIB_C_SOURCES),$$(call src_to_obj,$1,$$(f)))
LIB_S_OBJECTS_$1 := $$(foreach f,$$(LIB_S_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))
LIB_ASM_OBJECTS_$1 := $$(foreach f,$$(LIB_ASM_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))

LIB_CPP_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_CPP_SOURCES),$$(call src_to_pic_obj,$1,$$(f)))
LIB_C_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_C_SOURCES),$$(call src_to_pic_obj,$1,$$(f)))
LIB_S_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_S_SOURCES_$1),$$(call src_to_pic_obj,$1,$$(f)))
LIB_ASM_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_ASM_SOURCES_$1),$$(call src_to_pic_obj,$1,$$(f)))

LIB_OBJECTS_$1 := $$(LIB_CPP_OBJECTS_$1) $$(LIB_C_OBJECTS_$1) $$(LIB_S_OBJECTS_$1) $$(LIB_ASM_OBJECTS_$1)
LIB_PIC_OBJECTS_$1 := $$(LIB_CPP_PIC_OBJECTS_$1) $$(LIB_C_PIC_OBJECTS_$1) $$(LIB_S_PIC_OBJECTS_$1) $$(LIB_ASM_PIC_OBJECTS_$1)
ALL_OBJECTS_$1 := $$(BIN_OBJECTS_$1) $$(LIB_OBJECTS_$1) $$(LIB_PIC_OBJECTS_$1)
endef

$(foreach abi,$(BUILD_ABIS),$(eval $(call define_abi_objects,$(abi))))

EXE_TARGETS := $(foreach abi,$(BUILD_ABIS),exe-$(abi))
STATIC_TARGETS := $(foreach abi,$(BUILD_ABIS),static-$(abi))
SHARED_TARGETS := $(foreach abi,$(BUILD_ABIS),shared-$(abi))
ABI_TARGETS := $(EXE_TARGETS) $(STATIC_TARGETS) $(SHARED_TARGETS)
EXEC_OUTS := $(foreach abi,$(BUILD_ABIS),$(EXEC_OUT_$(abi)))
STATIC_OUTS := $(foreach abi,$(BUILD_ABIS),$(STATIC_OUT_$(abi)))
SHARED_OUTS := $(foreach abi,$(BUILD_ABIS),$(SHARED_OUT_$(abi)))
ALL_OBJECTS := $(foreach abi,$(BUILD_ABIS),$(ALL_OBJECTS_$(abi)))

# -----------------------------------
# Verbose mode
# -----------------------------------
VERBOSE ?= 0
ifeq ($(VERBOSE),1)
  Q :=
else
  Q := @
endif

# Suppress recursive-make directory enter/leave messages
MAKEFLAGS += --no-print-directory

# -----------------------------------
# Compilation rules
# -----------------------------------

define define_abi_rules
# C++ sources in src/bin (no PIC)
$$(call abi_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.cpp
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C++ (bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS) $$(CXXFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.$1.S files, preprocessed)
$$(call abi_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.$1.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.S files, preprocessed)
$$(call abi_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.$1.asm files, preprocessed)
$$(call abi_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.$1.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.asm files, preprocessed)
$$(call abi_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C++ sources in src/lib
$$(call abi_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.cpp
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C++ (lib, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(CXXFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C sources in src/lib
$$(call abi_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.c
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C (lib, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(ARCHFLAGS_$1) -x c -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C++ sources in src/lib compiled with PIC for shared library target
$$(call abi_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.cpp
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C++ (lib,pic,$1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(CXXFLAGS_$1) $$(ARCHFLAGS_$1) -fPIC -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C sources in src/lib compiled with PIC for shared library target
$$(call abi_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.c
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C (lib,pic,$1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(ARCHFLAGS_$1) -fPIC -x c -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.S files, preprocessed)
$$(call abi_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.$1.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.S files, preprocessed)
$$(call abi_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.S files, preprocessed) compiled with PIC
$$(call abi_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.$1.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(S_PICFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.S files, preprocessed) compiled with PIC
$$(call abi_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(S_PICFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.asm files, preprocessed)
$$(call abi_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.$1.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.asm files, raw assembly)
$$(call abi_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.asm files, preprocessed) compiled with PIC
$$(call abi_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.$1.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(ASM_PICFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.asm files, raw assembly) compiled with PIC
$$(call abi_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS) $$(ASM_PICFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

.PHONY: exe-$1
exe-$1: dep-incmap $$(EXEC_OUT_$1)

$$(EXEC_OUT_$1): $$(BIN_OBJECTS_$1) $$(LIB_OBJECTS_$1)
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "Link (exe, $1): $$@"
	$$(Q)$$(EXE_LINKER) $$(LDFLAGS_$1) $$(EXE_ARCHFLAGS_$1) -o $$@ $$^ $$(LDLIBS)

.PHONY: static-$1
static-$1: dep-incmap $$(STATIC_OUT_$1)

$$(STATIC_OUT_$1): $$(LIB_OBJECTS_$1)
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "Archive (static, $1): $$@"
	$$(Q)rm -f $$@
	$$(Q)$$(AR) rcs $$@ $$^

.PHONY: shared-$1
shared-$1: dep-incmap $$(SHARED_OUT_$1)

$$(SHARED_OUT_$1): $$(LIB_PIC_OBJECTS_$1)
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "Link (shared, $1): $$@"
	$$(Q)$$(SHARED_LINKER) -shared $$(LDFLAGS_$1) $$(SHARED_ARCHFLAGS_$1) -o $$@ $$^ $$(LDLIBS)
endef

$(foreach abi,$(BUILD_ABIS),$(eval $(call define_abi_rules,$(abi))))

# -----------------------------------
# Executable
# -----------------------------------
.DEFAULT_GOAL := all

all: dep-incmap $(BUILD_TARGETS)

exe: $(EXE_TARGETS)

# -----------------------------------
# Static library
# -----------------------------------
static: $(STATIC_TARGETS)

# -----------------------------------
# Shared library
# -----------------------------------
shared: $(SHARED_TARGETS)

# -----------------------------------
# Auto dependencies
# -----------------------------------
DEPS := $(ALL_OBJECTS:.o=.d)
-include $(DEPS)

# -----------------------------------
# PHONY targets
# -----------------------------------
.PHONY: help
help:
	@echo "Targets:"
	@echo "  all        Build enabled target/ABI combinations"
	@echo "  exe        Build executable for enabled ABIs"
	@echo "  static     Build static library for enabled ABIs"
	@echo "  shared     Build shared library for enabled ABIs"
	@echo "  exe-m32    Build 32-bit executable (with BUILD_M32=1)"
	@echo "  exe-m64    Build 64-bit executable (with BUILD_M64=1)"
	@echo "  static-m32 Build 32-bit static library (with BUILD_M32=1)"
	@echo "  static-m64 Build 64-bit static library (with BUILD_M64=1)"
	@echo "  shared-m32 Build 32-bit shared library (with BUILD_M32=1)"
	@echo "  shared-m64 Build 64-bit shared library (with BUILD_M64=1)"
	@echo "  tests      Run unit + system tests (if present)"
	@echo "  ut         Run unit tests"
	@echo "  sy         Run system tests"
	@echo "  clean      Remove build artefacts"
	@echo "  distclean  Same as clean"
	@echo ""
	@echo "Options:"
	@echo "  MODE=debug|release"
	@echo "  BUILD_M32=0|1        Enable 32-bit build graph (default: 0)"
	@echo "  BUILD_M64=0|1        Enable 64-bit build graph (default: 1)"
	@echo "  VERBOSE=1"
	@echo "  FILTER=<substring>   Filter tests by name (e.g. make tests FILTER=math)"

.PHONY: dep-incmap
dep-incmap:
	$(Q)mkdir -p "$(DEP_MAP_DIR)"
	$(Q)for d in $(DEP_NAMES); do \
		if [ -d "$(DEP_ROOT)/$$d/src/inc/$$d" ]; then \
			ln -sfn "$(DEP_ROOT_ABS)/$$d/src/inc/$$d" "$(DEP_MAP_DIR)/$$d"; \
		elif [ -d "$(DEP_ROOT)/$$d/src/inc" ]; then \
			ln -sfn "$(DEP_ROOT_ABS)/$$d/src/inc" "$(DEP_MAP_DIR)/$$d"; \
		fi; \
	done

.PHONY: ut
ut:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" all; \
		if [ -n "$(FILTER)" ]; then \
			echo "Running filtered unit tests (FILTER=$(FILTER))..."; \
			found=0; \
			for bin in "$(TST_UT_DIR)"/bld/TEST_*; do \
				if [ -x "$$bin" ] && [ -f "$$bin" ]; then \
					base="$$(basename "$$bin")"; \
					base_lc="$$(printf "%s" "$$base" | tr '[:upper:]' '[:lower:]')"; \
					filter_lc="$$(printf "%s" "$(FILTER)" | tr '[:upper:]' '[:lower:]')"; \
					case "$$base_lc" in \
						*$$filter_lc*) \
							echo "→ Running $$bin"; \
							"$$bin" || exit 1; \
							found=1; \
							;; \
					esac; \
				fi; \
			done; \
			if [ "$$found" -eq 0 ]; then \
				echo "No unit tests matched FILTER=$(FILTER)"; \
			fi; \
		else \
			$(MAKE) -C "$(TST_UT_DIR)" run; \
		fi; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

.PHONY: sy
sy: all
	@if [ -x "$(TST_SY_DIR)/runner" ]; then \
		FILTER="$(FILTER)" "$(TST_SY_DIR)/runner"; \
	else \
		echo "No system test runner found at $(TST_SY_DIR)/runner"; \
	fi

.PHONY: tests
tests: ut sy

.PHONY: clean clean-tests clean-all distclean

clean-all:
	$(Q)echo "Cleaning build artefacts..."
	$(Q)for d in "$(OBJ_DIR)" "$(OUT_DIR)"; do \
		mkdir -p "$$d"; \
		find "$$d" -mindepth 1 \( -type f -o -type l \) ! -name ".gitignore" -delete; \
		find "$$d" -mindepth 1 -type d -empty -delete; \
	done

clean-tests:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" clean; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

clean: clean-all clean-tests

distclean: clean

.PHONY: all exe static shared $(ABI_TARGETS) tests ut sy dep-incmap clean clean-all clean-tests distclean
