# --------------------------------------------------------------------
#
# !\file makefile
# !\brief Makefile for building the project.
# !\author Colin J.D. Stewart
#
# --------------------------------------------------------------------
#             Copyright (c) 2026. Colin J.D. Stewart
#                     All rights reserved
# --------------------------------------------------------------------

#
# DO NOT EDIT THIS FILE. FOR CUSTOMISATION

# -----------------------------------
# Directory layout
# -----------------------------------
SRC_DIR := src
BIN_DIR := $(SRC_DIR)/bin
LIB_DIR := $(SRC_DIR)/lib
INC_DIR := $(SRC_DIR)/inc

# automatically collect every subdirectory beneath the public include
# tree. This saves callers from having to add -I for each new component
# manually; the recursive find handles arbitrarily deep hierarchies.
#
# Note: the find pipes stderr to /dev/null in case the directory doesn't
# exist yet (e.g. early in a fresh checkout).
INC_SUBDIRS := $(shell find $(INC_DIR) -type d 2>/dev/null)
INC_SUBDIR_FLAGS := $(foreach dir,$(INC_SUBDIRS),-I$(dir))
OBJ_DIR := $(SRC_DIR)/bld
OUT_DIR := bld
profile_obj_dir = $(OBJ_DIR)/$(1)
profile_out_dir = $(OUT_DIR)/$(1)

# Prefer the sibling test tree while keeping src/tst/ut working for older
# projects. During migration, accept either tst/makefile or tst/ut/makefile.
TST_DIR := tst
LEGACY_TST_DIR := $(SRC_DIR)/tst
test_makefile = $(wildcard $(1)/Makefile $(1)/makefile)
TST_UT_DIRS := $(TST_DIR) $(TST_DIR)/ut $(LEGACY_TST_DIR)/ut
DETECTED_TST_UT_DIR := $(firstword $(foreach dir,$(TST_UT_DIRS),$(if $(call test_makefile,$(dir)),$(dir))))
TST_UT_DIR := $(if $(DETECTED_TST_UT_DIR),$(DETECTED_TST_UT_DIR),$(LEGACY_TST_DIR)/ut)
TST_SY_DIR := $(if $(wildcard $(TST_DIR)/sy),$(TST_DIR)/sy,$(LEGACY_TST_DIR)/sy)

# -----------------------------------
# Dependency include scanning (dep/*)
# -----------------------------------
DEP_ROOT := dep
DEP_ROOT_ABS := $(abspath $(DEP_ROOT))
# Keep the dependency include map shared across build profiles; the
# symlinked include tree itself is architecture-neutral.
DEP_MAP_DIR := $(OBJ_DIR)/depinc
DEP_NAMES := $(shell [ -d "$(DEP_ROOT)" ] && for p in "$(DEP_ROOT)"/*; do [ -d "$$p" ] && basename "$$p"; done || true)
DEP_INC_DIRS := $(wildcard $(DEP_ROOT)/*/src/inc)
DEP_INC_FLAGS := $(foreach dir,$(DEP_INC_DIRS),-I$(dir))

# -----------------------------------
# Toolchain
# -----------------------------------
CXX ?= g++
AR ?= ar
EXE_LINKER ?= $(CXX)
SHARED_LINKER ?= $(CXX)

# MODE and CXX_STD may be set in makefile.project.mk
MODE ?= debug
CXX_STD ?= c++20
FILTER ?= $(filter)

# -----------------------------------
# Assembly mode override helpers
# -----------------------------------

# Strip an optional .<profile> marker that appears immediately before the
# source extension, so:
#   foo.kernel.S -> foo.S
#   foo.user.asm -> foo.asm
strip_one_profile_marker = $(if $(filter %.$(2),$(basename $(1))),$(basename $(basename $(1)))$(suffix $(1)),$(1))
strip_profile_markers_impl = $(if $(strip $(1)),$(call strip_profile_markers_impl,$(wordlist 2,$(words $(1)),$(1)),$(call strip_one_profile_marker,$(2),$(firstword $(1)))),$(2))
strip_profile_marker = $(call strip_profile_markers_impl,$(ACTIVE_PROFILES),$(1))

# Convert a source path under src/ to its profile-specific object path under
# src/bld/<profile>/, while also stripping the optional profile marker from
# the basename.
src_to_obj = $(patsubst $(SRC_DIR)/%.cpp,$(call profile_obj_dir,$(1))/%.o,$(patsubst $(SRC_DIR)/%.c,$(call profile_obj_dir,$(1))/%.o,$(patsubst $(SRC_DIR)/%.S,$(call profile_obj_dir,$(1))/%.o,$(patsubst $(SRC_DIR)/%.asm,$(call profile_obj_dir,$(1))/%.o,$(call strip_profile_marker,$(2))))))
src_to_pic_obj = $(patsubst $(SRC_DIR)/%.cpp,$(call profile_obj_dir,$(1))/%.pic.o,$(patsubst $(SRC_DIR)/%.c,$(call profile_obj_dir,$(1))/%.pic.o,$(patsubst $(SRC_DIR)/%.S,$(call profile_obj_dir,$(1))/%.pic.o,$(patsubst $(SRC_DIR)/%.asm,$(call profile_obj_dir,$(1))/%.pic.o,$(call strip_profile_marker,$(2))))))

# Given a list of profile-flagged sources, derive the matching plain source
# names so they can be excluded from the normal source list.
flagged_to_plain = $(foreach f,$(1),$(call strip_profile_marker,$(f)))

# -----------------------------------
# Flags and options
# -----------------------------------
CPPFLAGS += -I$(INC_DIR) $(INC_SUBDIR_FLAGS) $(DEP_INC_FLAGS) -I$(DEP_MAP_DIR) -MMD -MP
CXXFLAGS += -std=$(CXX_STD) -Wall -Wextra -Wpedantic
LDFLAGS +=
LDLIBS +=
SFLAGS += $(filter-out -std=%,$(CXXFLAGS))
ASMFLAGS += $(filter-out -std=%,$(CXXFLAGS))
S_PICFLAGS += $(filter-out -std=%,$(CXXFLAGS)) -fPIC
ASM_PICFLAGS += $(filter-out -std=%,$(CXXFLAGS)) -fPIC

ifeq ($(MODE),release)
  CXXFLAGS += -O2 -DNDEBUG
else
  CXXFLAGS += -O0 -g
endif

# Project hooks
CPPFLAGS += $(USER_CPPFLAGS) -I$(DEP_MAP_DIR)
CXXFLAGS += $(USER_CXXFLAGS)
LDFLAGS += $(USER_LDFLAGS)
LDLIBS += $(USER_LDLIBS)
SFLAGS += $(USER_SFLAGS)
ASMFLAGS += $(USER_ASMFLAGS)
S_PICFLAGS += $(USER_S_PICFLAGS)
ASM_PICFLAGS += $(USER_ASM_PICFLAGS)

# -----------------------------------
# Architecture-specific compatibility helpers
# -----------------------------------

arch_filter_m32 = $(filter-out -m64 -m32 -mcmodel=%,$(1))
arch_filter_m64 = $(filter-out -m32 -m64,$(1))

COMPAT_ARCHFLAGS_m32 := -m32
COMPAT_ARCHFLAGS_m64 := -m64

# Bare linkers such as ld/ld.lld do not accept compiler-style -m32/-m64
# switches. Keep separate linker arch flags so projects that link via ld
# can rely on explicit emulation flags in USER_LDFLAGS instead.
is_ld_linker = $(strip $(filter ld ld.% %ld %ld.%,$(notdir $(1))))
COMPAT_CXXFLAGS_m32 := $(call arch_filter_m32,$(CXXFLAGS))
COMPAT_CXXFLAGS_m64 := $(call arch_filter_m64,$(CXXFLAGS))
COMPAT_LDFLAGS_m32 := $(call arch_filter_m32,$(LDFLAGS))
COMPAT_LDFLAGS_m64 := $(call arch_filter_m64,$(LDFLAGS))
COMPAT_SFLAGS_m32 := $(call arch_filter_m32,$(SFLAGS))
COMPAT_SFLAGS_m64 := $(call arch_filter_m64,$(SFLAGS))
COMPAT_ASMFLAGS_m32 := $(call arch_filter_m32,$(ASMFLAGS))
COMPAT_ASMFLAGS_m64 := $(call arch_filter_m64,$(ASMFLAGS))
COMPAT_S_PICFLAGS_m32 := $(call arch_filter_m32,$(S_PICFLAGS))
COMPAT_S_PICFLAGS_m64 := $(call arch_filter_m64,$(S_PICFLAGS))
COMPAT_ASM_PICFLAGS_m32 := $(call arch_filter_m32,$(ASM_PICFLAGS))
COMPAT_ASM_PICFLAGS_m64 := $(call arch_filter_m64,$(ASM_PICFLAGS))

# -----------------------------------
# Profile selection
# -----------------------------------
BUILD_PROFILES ?=
BUILD_M32 ?= 0
BUILD_M64 ?= 1

LEGACY_PROFILES :=

ifeq ($(BUILD_M32),1)
  LEGACY_PROFILES += m32
endif

ifeq ($(BUILD_M64),1)
  LEGACY_PROFILES += m64
endif

ACTIVE_PROFILES := $(strip $(if $(BUILD_PROFILES),$(BUILD_PROFILES),$(LEGACY_PROFILES)))

ifeq ($(strip $(ACTIVE_PROFILES)),)
  $(warning No build profiles enabled (set BUILD_PROFILES or BUILD_M32/BUILD_M64))
endif

SINGLE_PROFILE := $(if $(filter 1,$(words $(ACTIVE_PROFILES))),$(firstword $(ACTIVE_PROFILES)))

default_exec_out = $(call profile_out_dir,$(1))/$(BIN_NAME)
default_static_out = $(call profile_out_dir,$(1))/lib$(LIB_BASENAME).a
default_shared_out = $(call profile_out_dir,$(1))/lib$(LIB_BASENAME).so

ifneq ($(strip $(EXEC_OUT)),)
ifneq ($(words $(ACTIVE_PROFILES)),1)
  $(warning EXEC_OUT is ignored when multiple profiles are enabled; use PROFILE_<name>_EXEC_OUT or EXEC_OUT_<name>)
endif
endif

ifneq ($(strip $(STATIC_OUT)),)
ifneq ($(words $(ACTIVE_PROFILES)),1)
  $(warning STATIC_OUT is ignored when multiple profiles are enabled; use PROFILE_<name>_STATIC_OUT or STATIC_OUT_<name>)
endif
endif

ifneq ($(strip $(SHARED_OUT)),)
ifneq ($(words $(ACTIVE_PROFILES)),1)
  $(warning SHARED_OUT is ignored when multiple profiles are enabled; use PROFILE_<name>_SHARED_OUT or SHARED_OUT_<name>)
endif
endif

detect_profile_arch_from_cxxflags = $(if $(filter -m32,$(2)),m32,$(if $(filter -m64,$(2)),m64,))
resolved_profile_arch = $(strip $(if $(PROFILE_$1_ARCH),$(PROFILE_$1_ARCH),$(if $(filter m32 m64,$(1)),$(1),$(call detect_profile_arch_from_cxxflags,$(1),$(PROFILE_$1_CXXFLAGS)))))

default_archflags_for_arch = $(if $(filter m32,$(1)),$(COMPAT_ARCHFLAGS_m32),$(if $(filter m64,$(1)),$(COMPAT_ARCHFLAGS_m64),))
default_exe_archflags_for_arch = $(if $(filter m32,$(1)),$(if $(call is_ld_linker,$(2)),,$(COMPAT_ARCHFLAGS_m32)),$(if $(filter m64,$(1)),$(if $(call is_ld_linker,$(2)),,$(COMPAT_ARCHFLAGS_m64)),))
default_shared_archflags_for_arch = $(if $(filter m32,$(1)),$(if $(call is_ld_linker,$(2)),,$(COMPAT_ARCHFLAGS_m32)),$(if $(filter m64,$(1)),$(if $(call is_ld_linker,$(2)),,$(COMPAT_ARCHFLAGS_m64)),))

base_cxxflags_for_arch = $(if $(filter m32,$(1)),$(COMPAT_CXXFLAGS_m32),$(if $(filter m64,$(1)),$(COMPAT_CXXFLAGS_m64),$(CXXFLAGS)))
base_ldflags_for_arch = $(if $(filter m32,$(1)),$(COMPAT_LDFLAGS_m32),$(if $(filter m64,$(1)),$(COMPAT_LDFLAGS_m64),$(LDFLAGS)))
base_sflags_for_arch = $(if $(filter m32,$(1)),$(COMPAT_SFLAGS_m32),$(if $(filter m64,$(1)),$(COMPAT_SFLAGS_m64),$(SFLAGS)))
base_asmflags_for_arch = $(if $(filter m32,$(1)),$(COMPAT_ASMFLAGS_m32),$(if $(filter m64,$(1)),$(COMPAT_ASMFLAGS_m64),$(ASMFLAGS)))
base_s_picflags_for_arch = $(if $(filter m32,$(1)),$(COMPAT_S_PICFLAGS_m32),$(if $(filter m64,$(1)),$(COMPAT_S_PICFLAGS_m64),$(S_PICFLAGS)))
base_asm_picflags_for_arch = $(if $(filter m32,$(1)),$(COMPAT_ASM_PICFLAGS_m32),$(if $(filter m64,$(1)),$(COMPAT_ASM_PICFLAGS_m64),$(ASM_PICFLAGS)))

define init_profile
PROFILE_ARCH_$1 := $(call resolved_profile_arch,$1)

CPPFLAGS_$1 := $(CPPFLAGS) $(PROFILE_$1_CPPFLAGS)
CXXFLAGS_$1 := $(call base_cxxflags_for_arch,$(call resolved_profile_arch,$1)) $(PROFILE_$1_CXXFLAGS)
LDFLAGS_EXE_$1 := $(call base_ldflags_for_arch,$(call resolved_profile_arch,$1)) $(PROFILE_$1_LDFLAGS) $(PROFILE_$1_EXE_LDFLAGS)
LDFLAGS_SHARED_$1 := $(call base_ldflags_for_arch,$(call resolved_profile_arch,$1)) $(PROFILE_$1_LDFLAGS) $(PROFILE_$1_SHARED_LDFLAGS)
LDLIBS_EXE_$1 := $(LDLIBS) $(PROFILE_$1_LDLIBS) $(PROFILE_$1_EXE_LDLIBS)
LDLIBS_SHARED_$1 := $(LDLIBS) $(PROFILE_$1_LDLIBS) $(PROFILE_$1_SHARED_LDLIBS)
SFLAGS_$1 := $(call base_sflags_for_arch,$(call resolved_profile_arch,$1)) $(PROFILE_$1_SFLAGS)
ASMFLAGS_$1 := $(call base_asmflags_for_arch,$(call resolved_profile_arch,$1)) $(PROFILE_$1_ASMFLAGS)
S_PICFLAGS_$1 := $(call base_s_picflags_for_arch,$(call resolved_profile_arch,$1)) $(PROFILE_$1_S_PICFLAGS)
ASM_PICFLAGS_$1 := $(call base_asm_picflags_for_arch,$(call resolved_profile_arch,$1)) $(PROFILE_$1_ASM_PICFLAGS)

EXE_LINKER_$1 := $(if $(strip $(PROFILE_$1_EXE_LINKER)),$(PROFILE_$1_EXE_LINKER),$(EXE_LINKER))
SHARED_LINKER_$1 := $(if $(strip $(PROFILE_$1_SHARED_LINKER)),$(PROFILE_$1_SHARED_LINKER),$(SHARED_LINKER))

ARCHFLAGS_$1 := $(if $(strip $(PROFILE_$1_ARCHFLAGS)),$(PROFILE_$1_ARCHFLAGS),$(call default_archflags_for_arch,$(call resolved_profile_arch,$1)))
EXE_ARCHFLAGS_$1 := $(if $(strip $(PROFILE_$1_EXE_ARCHFLAGS)),$(PROFILE_$1_EXE_ARCHFLAGS),$(call default_exe_archflags_for_arch,$(call resolved_profile_arch,$1),$(if $(strip $(PROFILE_$1_EXE_LINKER)),$(PROFILE_$1_EXE_LINKER),$(EXE_LINKER))))
SHARED_ARCHFLAGS_$1 := $(if $(strip $(PROFILE_$1_SHARED_ARCHFLAGS)),$(PROFILE_$1_SHARED_ARCHFLAGS),$(call default_shared_archflags_for_arch,$(call resolved_profile_arch,$1),$(if $(strip $(PROFILE_$1_SHARED_LINKER)),$(PROFILE_$1_SHARED_LINKER),$(SHARED_LINKER))))

PROFILE_BUILD_EXE_$1 := $(if $(strip $(PROFILE_$1_BUILD_EXE)),$(PROFILE_$1_BUILD_EXE),$(BUILD_EXE))
PROFILE_BUILD_STATIC_$1 := $(if $(strip $(PROFILE_$1_BUILD_STATIC)),$(PROFILE_$1_BUILD_STATIC),$(BUILD_STATIC))
PROFILE_BUILD_SHARED_$1 := $(if $(strip $(PROFILE_$1_BUILD_SHARED)),$(PROFILE_$1_BUILD_SHARED),$(BUILD_SHARED))

EXEC_OUT_$1 := $(if $(strip $(PROFILE_$1_EXEC_OUT)),$(PROFILE_$1_EXEC_OUT),$(if $(strip $(EXEC_OUT_$1)),$(EXEC_OUT_$1),$(if $(and $(filter $1,$(SINGLE_PROFILE)),$(strip $(EXEC_OUT))),$(EXEC_OUT),$(call default_exec_out,$1))))
STATIC_OUT_$1 := $(if $(strip $(PROFILE_$1_STATIC_OUT)),$(PROFILE_$1_STATIC_OUT),$(if $(strip $(STATIC_OUT_$1)),$(STATIC_OUT_$1),$(if $(and $(filter $1,$(SINGLE_PROFILE)),$(strip $(STATIC_OUT))),$(STATIC_OUT),$(call default_static_out,$1))))
SHARED_OUT_$1 := $(if $(strip $(PROFILE_$1_SHARED_OUT)),$(PROFILE_$1_SHARED_OUT),$(if $(strip $(SHARED_OUT_$1)),$(SHARED_OUT_$1),$(if $(and $(filter $1,$(SINGLE_PROFILE)),$(strip $(SHARED_OUT))),$(SHARED_OUT),$(call default_shared_out,$1))))
endef

$(foreach profile,$(ACTIVE_PROFILES),$(eval $(call init_profile,$(profile))))

# -----------------------------------
# Source discovery
# -----------------------------------

BIN_SOURCES := $(wildcard $(BIN_DIR)/*.cpp)

LIB_CPP_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.cpp' || true)
LIB_C_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.c' || true)

# ------------------------------------
# Object file lists
# ------------------------------------

define define_profile_objects
BIN_S_FLAGGED_SOURCES_$1 := $(wildcard $(BIN_DIR)/*.$1.S)
BIN_S_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(BIN_S_FLAGGED_SOURCES_$1)),$(wildcard $(BIN_DIR)/*.S))

BIN_ASM_FLAGGED_SOURCES_$1 := $(wildcard $(BIN_DIR)/*.$1.asm)
BIN_ASM_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(BIN_ASM_FLAGGED_SOURCES_$1)),$(wildcard $(BIN_DIR)/*.asm))

LIB_S_FLAGGED_SOURCES_$1 := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.$1.S' || true)
LIB_S_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(LIB_S_FLAGGED_SOURCES_$1)),$(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.S' || true))

LIB_ASM_FLAGGED_SOURCES_$1 := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.$1.asm' || true)
LIB_ASM_PLAIN_SOURCES_$1 := $(filter-out $(call flagged_to_plain,$$(LIB_ASM_FLAGGED_SOURCES_$1)),$(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.asm' || true))

BIN_S_SOURCES_$1 := $$(BIN_S_PLAIN_SOURCES_$1) $$(BIN_S_FLAGGED_SOURCES_$1)
BIN_ASM_SOURCES_$1 := $$(BIN_ASM_PLAIN_SOURCES_$1) $$(BIN_ASM_FLAGGED_SOURCES_$1)

LIB_S_SOURCES_$1 := $$(LIB_S_PLAIN_SOURCES_$1) $$(LIB_S_FLAGGED_SOURCES_$1)
LIB_ASM_SOURCES_$1 := $$(LIB_ASM_PLAIN_SOURCES_$1) $$(LIB_ASM_FLAGGED_SOURCES_$1)

LIB_SOURCES_$1 := $(LIB_CPP_SOURCES) $(LIB_C_SOURCES) $$(LIB_S_SOURCES_$1) $$(LIB_ASM_SOURCES_$1)

BIN_OBJECTS_$1 := $$(foreach f,$$(BIN_SOURCES),$$(call src_to_obj,$1,$$(f)))
BIN_OBJECTS_$1 += $$(foreach f,$$(BIN_S_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))
BIN_OBJECTS_$1 += $$(foreach f,$$(BIN_ASM_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))

LIB_CPP_OBJECTS_$1 := $$(foreach f,$$(LIB_CPP_SOURCES),$$(call src_to_obj,$1,$$(f)))
LIB_C_OBJECTS_$1 := $$(foreach f,$$(LIB_C_SOURCES),$$(call src_to_obj,$1,$$(f)))
LIB_S_OBJECTS_$1 := $$(foreach f,$$(LIB_S_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))
LIB_ASM_OBJECTS_$1 := $$(foreach f,$$(LIB_ASM_SOURCES_$1),$$(call src_to_obj,$1,$$(f)))

LIB_CPP_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_CPP_SOURCES),$$(call src_to_pic_obj,$1,$$(f)))
LIB_C_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_C_SOURCES),$$(call src_to_pic_obj,$1,$$(f)))
LIB_S_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_S_SOURCES_$1),$$(call src_to_pic_obj,$1,$$(f)))
LIB_ASM_PIC_OBJECTS_$1 := $$(foreach f,$$(LIB_ASM_SOURCES_$1),$$(call src_to_pic_obj,$1,$$(f)))

LIB_OBJECTS_$1 := $$(LIB_CPP_OBJECTS_$1) $$(LIB_C_OBJECTS_$1) $$(LIB_S_OBJECTS_$1) $$(LIB_ASM_OBJECTS_$1)
LIB_PIC_OBJECTS_$1 := $$(LIB_CPP_PIC_OBJECTS_$1) $$(LIB_C_PIC_OBJECTS_$1) $$(LIB_S_PIC_OBJECTS_$1) $$(LIB_ASM_PIC_OBJECTS_$1)
ALL_OBJECTS_$1 := $$(BIN_OBJECTS_$1) $$(LIB_OBJECTS_$1) $$(LIB_PIC_OBJECTS_$1)
endef

$(foreach profile,$(ACTIVE_PROFILES),$(eval $(call define_profile_objects,$(profile))))

EXE_TARGETS := $(foreach profile,$(ACTIVE_PROFILES),$(if $(filter 1,$(PROFILE_BUILD_EXE_$(profile))),exe-$(profile)))
STATIC_TARGETS := $(foreach profile,$(ACTIVE_PROFILES),$(if $(filter 1,$(PROFILE_BUILD_STATIC_$(profile))),static-$(profile)))
SHARED_TARGETS := $(foreach profile,$(ACTIVE_PROFILES),$(if $(filter 1,$(PROFILE_BUILD_SHARED_$(profile))),shared-$(profile)))
PROFILE_TARGETS := $(EXE_TARGETS) $(STATIC_TARGETS) $(SHARED_TARGETS)
EXEC_OUTS := $(foreach profile,$(ACTIVE_PROFILES),$(if $(filter 1,$(PROFILE_BUILD_EXE_$(profile))),$(EXEC_OUT_$(profile))))
STATIC_OUTS := $(foreach profile,$(ACTIVE_PROFILES),$(if $(filter 1,$(PROFILE_BUILD_STATIC_$(profile))),$(STATIC_OUT_$(profile))))
SHARED_OUTS := $(foreach profile,$(ACTIVE_PROFILES),$(if $(filter 1,$(PROFILE_BUILD_SHARED_$(profile))),$(SHARED_OUT_$(profile))))
ALL_OBJECTS := $(foreach profile,$(ACTIVE_PROFILES),$(ALL_OBJECTS_$(profile)))

ifeq ($(strip $(PROFILE_TARGETS)),)
  $(warning No build targets enabled across active profiles)
endif

# -----------------------------------
# Verbose mode
# -----------------------------------
VERBOSE ?= 0
ifeq ($(VERBOSE),1)
  Q :=
else
  Q := @
endif

# Suppress recursive-make directory enter/leave messages
MAKEFLAGS += --no-print-directory

# -----------------------------------
# Compilation rules
# -----------------------------------

define define_profile_rules
# C++ sources in src/bin (no PIC)
$$(call profile_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.cpp
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C++ (bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS_$1) $$(CXXFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.$1.S files, preprocessed)
$$(call profile_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.$1.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS_$1) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.S files, preprocessed)
$$(call profile_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS_$1) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.$1.asm files, preprocessed)
$$(call profile_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.$1.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS_$1) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/bin (.asm files, preprocessed)
$$(call profile_obj_dir,$1)/bin/%.o: $$(BIN_DIR)/%.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, bin, $1): $$<"
	$$(Q)$$(CXX) $$(CPPFLAGS_$1) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C++ sources in src/lib
$$(call profile_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.cpp
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C++ (lib, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(CXXFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C sources in src/lib
$$(call profile_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.c
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C (lib, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(ARCHFLAGS_$1) -x c -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C++ sources in src/lib compiled with PIC for shared library target
$$(call profile_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.cpp
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C++ (lib,pic,$1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(CXXFLAGS_$1) $$(ARCHFLAGS_$1) -fPIC -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# C sources in src/lib compiled with PIC for shared library target
$$(call profile_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.c
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "C (lib,pic,$1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(ARCHFLAGS_$1) -fPIC -x c -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.S files, preprocessed)
$$(call profile_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.$1.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.S files, preprocessed)
$$(call profile_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(SFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.S files, preprocessed) compiled with PIC
$$(call profile_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.$1.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(S_PICFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.S files, preprocessed) compiled with PIC
$$(call profile_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.S
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.S, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(S_PICFLAGS_$1) $$(ARCHFLAGS_$1) -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.asm files, preprocessed)
$$(call profile_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.$1.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.asm files, raw assembly)
$$(call profile_obj_dir,$1)/lib/%.o: $$(LIB_DIR)/%.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(ASMFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.$1.asm files, preprocessed) compiled with PIC
$$(call profile_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.$1.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(ASM_PICFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

# Assembly sources in src/lib (.asm files, raw assembly) compiled with PIC
$$(call profile_obj_dir,$1)/lib/%.pic.o: $$(LIB_DIR)/%.asm
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "ASM (.asm, pic, $1): $$<"
	$$(Q)$$(CXX) -I$$(INC_DIR)/$$(dir $$*) $$(CPPFLAGS_$1) $$(ASM_PICFLAGS_$1) $$(ARCHFLAGS_$1) -x assembler-with-cpp -MT $$@ -MF $$(@:.o=.d) -c $$< -o $$@

.PHONY: exe-$1
exe-$1: dep-incmap $$(EXEC_OUT_$1)

$$(EXEC_OUT_$1): $$(BIN_OBJECTS_$1) $$(LIB_OBJECTS_$1)
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "Link (exe, $1): $$@"
	$$(Q)$$(EXE_LINKER_$1) $$(LDFLAGS_EXE_$1) $$(EXE_ARCHFLAGS_$1) -o $$@ $$^ $$(LDLIBS_EXE_$1)

.PHONY: static-$1
static-$1: dep-incmap $$(STATIC_OUT_$1)

$$(STATIC_OUT_$1): $$(LIB_OBJECTS_$1)
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "Archive (static, $1): $$@"
	$$(Q)rm -f $$@
	$$(Q)$$(AR) rcs $$@ $$^

.PHONY: shared-$1
shared-$1: dep-incmap $$(SHARED_OUT_$1)

$$(SHARED_OUT_$1): $$(LIB_PIC_OBJECTS_$1)
	$$(Q)mkdir -p $$(dir $$@)
	$$(Q)echo "Link (shared, $1): $$@"
	$$(Q)$$(SHARED_LINKER_$1) -shared $$(LDFLAGS_SHARED_$1) $$(SHARED_ARCHFLAGS_$1) -o $$@ $$^ $$(LDLIBS_SHARED_$1)
endef

$(foreach profile,$(ACTIVE_PROFILES),$(eval $(call define_profile_rules,$(profile))))

# -----------------------------------
# Executable
# -----------------------------------
.DEFAULT_GOAL := all

all: dep-incmap $(PROFILE_TARGETS)

exe: $(EXE_TARGETS)

# -----------------------------------
# Static library
# -----------------------------------
static: $(STATIC_TARGETS)

# -----------------------------------
# Shared library
# -----------------------------------
shared: $(SHARED_TARGETS)

# -----------------------------------
# Auto dependencies
# -----------------------------------
DEPS := $(ALL_OBJECTS:.o=.d)
-include $(DEPS)

# -----------------------------------
# PHONY targets
# -----------------------------------
.PHONY: help
help:
	@echo "Targets:"
	@echo "  all           Build enabled target/profile combinations"
	@echo "  exe           Build executables for enabled profiles"
	@echo "  static        Build static libraries for enabled profiles"
	@echo "  shared        Build shared libraries for enabled profiles"
	@echo "  exe-<profile> Build one profile's executable"
	@echo "  static-<profile> Build one profile's static library"
	@echo "  shared-<profile> Build one profile's shared library"
	@echo "  tests      Run unit + system tests (if present)"
	@echo "  ut         Run unit tests"
	@echo "  sy         Run system tests"
	@echo "  clean      Remove build artefacts"
	@echo ""
	@echo "Options:"
	@echo "  MODE=debug|release"
	@echo "  BUILD_PROFILES=\"name...\"  Enable named build profiles"
	@echo "  BUILD_M32=0|1        Enable 32-bit build graph (default: 0)"
	@echo "  BUILD_M64=0|1        Enable 64-bit build graph (default: 1)"
	@echo "  PROFILE_<name>_...   Profile-specific overrides for flags, outputs, and target enables"
	@echo "  VERBOSE=1"
	@echo "  FILTER=<substring>   Filter tests by name (e.g. make tests FILTER=math)"

.PHONY: dep-incmap
dep-incmap:
	$(Q)mkdir -p "$(DEP_MAP_DIR)"
	$(Q)for d in $(DEP_NAMES); do \
		if [ -d "$(DEP_ROOT)/$$d/src/inc/$$d" ]; then \
			ln -sfn "$(DEP_ROOT_ABS)/$$d/src/inc/$$d" "$(DEP_MAP_DIR)/$$d"; \
		elif [ -d "$(DEP_ROOT)/$$d/src/inc" ]; then \
			ln -sfn "$(DEP_ROOT_ABS)/$$d/src/inc" "$(DEP_MAP_DIR)/$$d"; \
		fi; \
	done

.PHONY: ut
ut:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" all; \
		if [ -n "$(FILTER)" ]; then \
			echo "Running filtered unit tests (FILTER=$(FILTER))..."; \
			found=0; \
			for bin in "$(TST_UT_DIR)"/bld/TEST_*; do \
				if [ -x "$$bin" ] && [ -f "$$bin" ]; then \
					base="$$(basename "$$bin")"; \
					base_lc="$$(printf "%s" "$$base" | tr '[:upper:]' '[:lower:]')"; \
					filter_lc="$$(printf "%s" "$(FILTER)" | tr '[:upper:]' '[:lower:]')"; \
					case "$$base_lc" in \
						*$$filter_lc*) \
							echo "→ Running $$bin"; \
							"$$bin" || exit 1; \
							found=1; \
							;; \
					esac; \
				fi; \
			done; \
			if [ "$$found" -eq 0 ]; then \
				echo "No unit tests matched FILTER=$(FILTER)"; \
			fi; \
		else \
			$(MAKE) -C "$(TST_UT_DIR)" run; \
		fi; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

.PHONY: sy
sy: all
	@if [ -x "$(TST_SY_DIR)/runner" ]; then \
		FILTER="$(FILTER)" "$(TST_SY_DIR)/runner"; \
	else \
		echo "No system test runner found at $(TST_SY_DIR)/runner"; \
	fi

.PHONY: tests
tests: ut sy

.PHONY: clean clean-tests clean-all distclean

clean-all:
	$(Q)echo "Cleaning build artefacts..."
	$(Q)for d in "$(OBJ_DIR)" "$(OUT_DIR)"; do \
		mkdir -p "$$d"; \
		find "$$d" -mindepth 1 \( -type f -o -type l \) ! -name ".gitignore" -delete; \
		find "$$d" -mindepth 1 -type d -empty -delete; \
	done

clean-tests:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" clean; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

clean: clean-all clean-tests

.PHONY: all exe static shared $(PROFILE_TARGETS) tests ut sy dep-incmap clean clean-all clean-tests distclean
